package za.ac.alis.service;

import org.openpdf.text.*;
import org.openpdf.text.pdf.PdfWriter;
import za.ac.alis.entities.SummaryReport;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

@Service
public class PdfReportService {

    @Transactional(readOnly = true)
    public byte[] generateComplianceReportPdf(SummaryReport report) throws DocumentException, IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();

        Document document = new Document(PageSize.A4, 50, 50, 60, 60);
        PdfWriter.getInstance(document, baos);
        document.open();

        // ─── HEADER ───────────────────────────────────────────────────────────────
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Color.BLACK);
        Paragraph title = new Paragraph("COMPLIANCE ANALYSIS REPORT", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(20);
        document.add(title);

        // ─── METADATA ─────────────────────────────────────────────────────────────
        Font metaFont     = FontFactory.getFont(FontFactory.HELVETICA, 11);
        Font boldMetaFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11);

        // FIX 1: Use getActName() from the linked Act — not text scanning
        document.add(new Paragraph("Law / Act     : " + getLawName(report), boldMetaFont));

        // FIX 2: Document has getTitle(), not getFilename()
        document.add(new Paragraph("File Analyzed : " + report.getDocument().getTitle(), metaFont));
        document.add(new Paragraph("Status        : " + report.getDocument().getStatus(), metaFont));
        document.add(new Paragraph("Generated On  : " + report.getGeneratedAt(), metaFont));
        document.add(Chunk.NEWLINE);

        // ─── EXECUTIVE SUMMARY ────────────────────────────────────────────────────
        Font sectionTitleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Color.BLACK);
        Paragraph summaryTitle = new Paragraph("EXECUTIVE SUMMARY", sectionTitleFont);
        summaryTitle.setSpacingAfter(10);
        document.add(summaryTitle);

        // FIX 3: SummaryReport has aiExplanation and aiRecommendation — not getReportText() or getSuggestionText()
        String reportText = resolveReportText(report);
        addFormattedText(document, reportText);

        // ─── AI RECOMMENDATION ────────────────────────────────────────────────────
        if (report.getAiRecommendation() != null && !report.getAiRecommendation().isBlank()) {
            document.add(Chunk.NEWLINE);
            document.add(new Paragraph("AI RECOMMENDATION", sectionTitleFont));
            document.add(new Paragraph(report.getAiRecommendation(), metaFont));
        }

        // ─── SIMILARITY SCORE ─────────────────────────────────────────────────────
        if (report.getSimilarityScore() != null) {
            document.add(Chunk.NEWLINE);
            document.add(new Paragraph(
                "Similarity Score : " + report.getSimilarityScore() + "%",
                boldMetaFont
            ));
        }

        // ─── RISK LEGEND ──────────────────────────────────────────────────────────
        document.add(Chunk.NEWLINE);
        document.add(new Paragraph("Risk Legend:", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12)));

        Font highFont   = FontFactory.getFont(FontFactory.HELVETICA, 10, Color.RED);
        Font mediumFont = FontFactory.getFont(FontFactory.HELVETICA, 10, new Color(255, 165, 0)); // FIX 4: Color.ORANGE doesn't exist in java.awt.Color
        Font lowFont    = FontFactory.getFont(FontFactory.HELVETICA, 10, new Color(0, 128, 0));   // dark green for LOW

        document.add(new Paragraph("HIGH SEVERITY    - Immediate action required (void or unfair terms)", highFont));
        document.add(new Paragraph("MEDIUM SEVERITY  - Review and amend recommended", mediumFont));
        document.add(new Paragraph("LOW SEVERITY     - Minor review suggested", lowFont));

        // ─── FOOTER ───────────────────────────────────────────────────────────────
        document.add(Chunk.NEWLINE);
        Font footerFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 9, Color.GRAY);
        Paragraph footer = new Paragraph(
            "This report was generated by ALIS Legal Compliance System • Confidential • Not Legal Advice",
            footerFont
        );
        footer.setAlignment(Element.ALIGN_CENTER);
        document.add(footer);

        document.close();
        return baos.toByteArray();
    }

    // ─── HELPERS ──────────────────────────────────────────────────────────────────

    /**
     * Resolves the main body text for the report.
     * Priority: aiExplanation → aiRecommendation → lawRule suggestion → fallback message
     */
    private String resolveReportText(SummaryReport report) {
        if (report.getAiExplanation() != null && !report.getAiExplanation().isBlank()) {
            return report.getAiExplanation();
        }
        if (report.getAiRecommendation() != null && !report.getAiRecommendation().isBlank()) {
            return report.getAiRecommendation();
        }
        if (report.getLawRule() != null && report.getLawRule().getSuggestion() != null) {
            return report.getLawRule().getSuggestion();
        }
        return "No detailed findings available.";
    }

    /**
     * Resolves the law/act name directly from the entity relationship.
     * FIX: No longer uses fragile text scanning — reads from the Act entity.
     */
    private String getLawName(SummaryReport report) {
        try {
            if (report.getLawRule() != null
                    && report.getLawRule().getAct() != null
                    && report.getLawRule().getAct().getActName() != null) {
                return report.getLawRule().getAct().getActName();
            }
        } catch (Exception e) {
            // Guard against any lazy-load edge case
        }
        return "South African Legislation";
    }

    /**
     * Renders multi-line text into the PDF, one paragraph per line.
     */
    private void addFormattedText(Document document, String fullText) throws DocumentException {
        if (fullText == null || fullText.trim().isEmpty()) {
            document.add(new Paragraph("No detailed findings available.",
                    FontFactory.getFont(FontFactory.HELVETICA, 11)));
            return;
        }

        Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 11);
        String[] lines = fullText.split("\\r?\\n");

        for (String line : lines) {
            if (line.trim().isEmpty()) {
                document.add(Chunk.NEWLINE);
                continue;
            }
            Paragraph p = new Paragraph(line.trim(), normalFont);
            p.setSpacingAfter(2f);
            document.add(p);
        }
    }
}